[package]
name = "math"
version = "0.1.0"
authors = ["illuminator3 <48388251+illuminator3@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"